version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    versioning-strategy: increase
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/frontend"
    versioning-strategy: increase
    schedule:
      interval: "daily"
